### ISSUE TITLE
Validate Condo Stack Tool in ArcGIS 10.6

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelProcessingTools#10]
https://www.sco.wisc.edu/parcels/tools/#Stack

**Comment by rhalton** [comment]
could not get this to work.

**Comment by codiesee** [comment]
Reopening issue - looks like this tool will need further testing in Arc 10.6 and possibly triage.

**Comment by codiesee** [comment]
Below is a screen capture taken of RH's error: 
![image](https://user-images.githubusercontent.com/7830695/47853796-e1ab9800-ddad-11e8-9ade-5968bf01abee.png)

**Comment by codiesee** [comment]
Made changes (with RH) to prevent any possible scenarios where an intermediary file leftover from previous (failed) execution of the tool would be left behind. Intermediary files will cause tool to fail because of file locks (cant overwrite).  Issue now closed.
