### ISSUE TITLE
Validate Address Tool in ArcGIS 10.6

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelProcessingTools#7]
https://www.sco.wisc.edu/parcels/tools/

**Comment by rhalton** [comment]
could not get this one to work.

**Comment by codiesee** [comment]
Address Parsing Tool requires further testing on ArcGIS 10.6, and possibly some required triage. Re-opening this issue.

**Comment by codiesee** [comment]
Validated on ArcGIS 10.6 (RH's machine), closing issue.
